---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
  namespace: default
spec:
  profile:
    displayName: Guest User
    email: guest@example.com
    picture: https://avatars.dicebear.com/api/avataaars/guest.svg?background=%23fff
  memberOf: [guests]

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guests
  namespace: default
spec:
  type: group
  profile:
    displayName: Guests
  children: []

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: An example of a Backstage application.
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: website
  lifecycle: experimental
  owner: group:guests   # ← Aquí ya está cambiado para que los guests tengan acceso total